### ISSUE TITLE
music channel (needs closure)

### ISSUE THREAD

**Issue by ghost** [TheCodeMonkeys/community-suggestions#10]
I wanna see a channel where people can post their music playlists or favourite tracks, it's interesting and cool to listen to what other people listen to :)

**Comment by Softizo** [comment]
You probably listen to darude sandstorm or shooting stars

**Comment by Caaz** [comment]
Not really too programming related but neither was gaming and its been a decent outlet for some people. I too am interested in picking up music from others so maybe thisll be a nice addition.

**Comment by ghost** [comment]
@Softizo very wise choice, but i prefer blue (da ba dee)

**Comment by Softizo** [comment]
@Cliffside-Dev But that's bad.

**Comment by ghost** [comment]
sounds good to me, lots of other servers have this as well and it's pretty nice

**Comment by ghost** [comment]
it is now done

**Comment by hexed** [comment]
As sated this is completed, suggestion closed.
