### ISSUE TITLE
be a doge and move development up and put general in there

### ISSUE THREAD

**Issue by canislupaster** [TheCodeMonkeys/community-suggestions#11]
development is important and general is general development

logic™️

**Comment by ghost** [comment]
no because general isnt generally about development it's to generally to do with development and things relating to it

logic(TM)

**Comment by canislupaster** [comment]
general isnt generally about development it's to generally to do with development and things relating to it

THAT IS NOT LOGIC

**Comment by ghost** [comment]
how so??

**Comment by spikespaz** [comment]
It is just a conflicting sentence but I understand what you're saying.

What about creating a second #general for both categories? General Chat and General Development?

**Comment by canislupaster** [comment]
our general chat is already off-topic @spikespaz

**Comment by hexed** [comment]
I think we should make a off topic category.
