### ISSUE TITLE
Title Change for #General

### ISSUE THREAD

**Issue by Lurgypai** [TheCodeMonkeys/community-suggestions#12]
I would suggest changing the title of #general to #general-programming, as it is often misused.
I check #general to see if anyone needs help, but I more often find myself reading useless information and combing it for anything relevant.

**Comment by ghost** [comment]
this was previously denied (see change #3 and #4 )

**Comment by Lurgypai** [comment]
k thx. Still encourage but oh well. The off topic chat in general is getting worse tho.
