### ISSUE TITLE
Bot to sync the #welcome channel message with a rules repo README.md

### ISSUE THREAD

**Issue by spikespaz** [TheCodeMonkeys/community-suggestions#14]
Create a repository called TheCodeMonkeys/server-rules and use the README.md to track changes and host the markup.

Create a simple bot that can be plugged into GitHub webhook and edit/update the message every time a rule is changed.

The goal would be to allow pull-requests for rule changes (subject to staff review) and allow Admins or Srs to edit the rule channel with proper markup formatting so that the rich styling isn't lost in the copy-change-paste that we do so much.

We would need to split placement of images into their own messages, probably require custom parsing to make the formatting convertible between the MD variations. Also, split at every 2000 characters.

**Comment by ghost** [comment]
seems a bit complex for a solution that can be fixed by just... suggesting changes on the github

**Comment by spikespaz** [comment]
Like I said, staff can't edit eachother's messages. This way, we can edit the repo and have changes reflected. It isn't too complicated, I could have a mockup in a day (sooner if I wasn't rusty). Besides, we're programmers. Let's automate shit!

**Comment by ghost** [comment]
you can assign yourself to host it then if someone else doesnt havethe oppurtunity or shits

this could also be implemented into codekey, but i do not agree that that thing should ever be added to at this point

**Comment by imandings** [comment]
While I like this idea and it could be achieved, I wonder if it's better to just double up with these changes - have a repository for rules to be in and when changes made we update it, versus using the bot for it.
