### ISSUE TITLE
Colloquially rename sections?

### ISSUE THREAD

**Issue by spikespaz** [TheCodeMonkeys/community-suggestions#15]
META to `dev_loop0` (`/dev/loop0` loopback device)
GENERAL to `dev_sda1` (`/dev/sda1` data partition)
DEVELOPMENT to `dev_sdb0` (`/dev/sdb0` primary data partition of second HDD)
COMPUTERS to `dev_sdb1` (`/dev/sdb1` secondary data partition of second HDD)
LOW LEVEL to `dev_sdb2` (`/dev/sdb2` tertiary data partition of second HDD)
SPAM to `dev_null` (`/dev/null`)
STAFF I have no idea, suggestions?
VOICE to `dev_snd` (`/dev/snd` sound devices directory)

**Comment by ghost** [comment]
no, just impractical and really useless imho - they work more than well now and don't need to be changed, and I think it can be more confusing even to be using file system structures that don't correspond with the actual catergory names

**Comment by hexed** [comment]
I don’t feel this would work. As this server is not just linux.
