### ISSUE TITLE
Delete #shout-outs-talk

### ISSUE THREAD

**Issue by ghost** [TheCodeMonkeys/community-suggestions#2]
The context is important sometimes and better off in shoutouts rather thana  seperate channel
(context infront of you)

**Comment by canislupaster** [comment]
Tbh i like shout outs as mini announcements, not mini announcement chat
but not sure if shoutouts-talk is a solution for that

**Comment by ghost** [comment]
we must protest, my son

**Comment by spikespaz** [comment]
#shout-outs is like community announcements. A log, if you will. Hell, even Tweets. But when people start talking about each post, it becomes cluttered and difficult for everyone to see that the announcement was. It's not a room for conversation and never will be.

**Comment by spikespaz** [comment]
It seems like most of the staff agrees (there was conversation in the staff text channels) that this is not a good idea. I won't close the issue yet, but I'm adding the `wontfix` label.

**Comment by spikespaz** [comment]
You've gotten three people, maybe more, disagreeing. There was some discussion about it in the staff chat, and I think it was mostly decided that this needs to not change. If I'm wrong, someone may re-open this at their leisure.
