### ISSUE TITLE
Rename #general to #discussion

### ISSUE THREAD

**Issue by spikespaz** [TheCodeMonkeys/community-suggestions#3]
Why?

`#general` typically in servers has conversation redirected to relevant channels. We don't do that; we allow conversations and questions of any topic to be asked and discussed in there, and only redirect to the relevant channels when there are a lot of people talking.

It's just an unimportant semantic, but it's a small improvement that can be made in my opinion.

**Comment by bpeters132** [comment]
what about.... `#general-discussion`

**Comment by teenangst** [comment]
I think `#general` works, as the channel is pretty ... `#general`

**Comment by spikespaz** [comment]
Yes but while `#general` works, people still might get the impression that it's only for things that don't fit into a category. `#general` is probably the channel that everybody looks at the most, besides `#staff-chat` (which should not be), so people should be able to ask any question for the scope of the server. Then, if that channel gets flooded, `@Staff` can redirect conversation to the appropriate channels. @teenangst 

`#general-discussion` is originally what I thought of, but the I realized that "general" was implied, and besides, the name is too long compared to other text channels so should be shortened for aesthetic reasons. @bpeters132 

Either way, I don't think `#general` is a very good name, it can be misleading, as if programming discussion that *is* categorized for another channel is *off-topic* specifically for `#general`.

**Comment by ghost** [comment]
I don't think #discussions would work, personally. #general sounds like a channel where you can talk about... anything in general, which I think is good because it doesn't put a limit on what people can ask about. However, look at the python server, for example, which do have a specific language they focus on, they use a #python channel and a #off-topic channel. If this were to be changed, I think it should be #coding-general

**Comment by atonylind** [comment]
Honestly I thought general was a default that discord required.

**Comment by moolicc** [comment]
I think it's just the channel that discord creates when you create a server. But I have to agree with Cliff.
 --- "The why is this a thing guy"

**Comment by atonylind** [comment]
As staff, we have a lot of power. I don't think that it is unreasonable to spin up temp channels, or direct users to use other channels if the amount of cross talk gets high. I also think that we have a lot of general channels as is. 

The whole general category is really just additional overflow channels for general imho.

**Comment by spikespaz** [comment]
@atonylind I don't know who you are by this name.

Also, can everyone either add the 👎 or 👍 emojis to the top level post to show your support/disapproval?

Just to get a head count.

**Comment by ghost** [comment]
i wanna note btw, i agree with antony  in the idea that we have a crap ton of general channels considering the much smaller amount of people we actually get in a day, that a lot more channels get a whole less activity not a whole less total channels with a whole more activity

**Comment by canislupaster** [comment]
I think having more focused channels is a good idea, but only if it's active enough. Either way, we'll never have enough channels to cover the whole scope of programming, so the overflow goes in #general and the stuff that aren't programming go in #off-topic . Maybe something we can do is limit #general to only programming. My problem with #discussion is that #discussion sounds completely separate from general programming questions. So maybe we can do something like #programming and the topic of the channel redirecting people. I also think #software is too wide, maybe we need #desktop and such.

**Comment by atonylind** [comment]
There are several things that need balanced here, the number of channels, the activity in channels, and the topic of the available channels. I think when we were doing the language specific channels that there was too much siloing , and this resulted in less overall activity. I also think that the current layout with web frontend/backend is a bit too focused on web technologies.

Maybe change development to  include OOP, scripting, web, ...

I also think we could get rid of code-review in favor of just posting the code you need help with in the channel.

**Comment by spikespaz** [comment]
I really agree that the channels need to be changed. I would actually prefer to remove some of the niche channels (all of them) and re-add based on suggestions and what we see people need. Obviously, the point of this is to be adaptive to what people need and there will me more needs as the server grows.

So it seems like there really isn't any support for the topic of this issue, and for the sake of organization, if one of you people wants to continue the channel conversation, make a new issue.

Thanks! Gonna close this one.

**Comment by bpeters132** [comment]
But if it's related to this issue. It should be continued on this issue.

**Comment by canislupaster** [comment]
ok then...

**Comment by ghost** [comment]
Logic lmao

**Comment by spikespaz** [comment]
It's a completely separate discussion and needs to move to a new thread. This thread was about *one* channel name. This needs to remain closed.
