### ISSUE TITLE
Change #general to #coding

### ISSUE THREAD

**Issue by ghost** [TheCodeMonkeys/community-suggestions#4]
I propose a change to #general to #coding. (Reference the #discussion proposal maybe?) as it shows it’s a dedicated channel to the servers main topic: Coding - it’s in the name. It means newer users are much more comfortable with seeing the, may I say, EXCESS of text channels we have, when they just wanna ask a question about their code, and get overwhelmed and either look elsewhere or have to ask around. A example of where general is substituted for a more specialised channel instead is the Python server we’re partnered with, who successfully did this with #python for the main topic and #off-topic for misc. 

Add a thumbs up/down to this for your opinion and leave a comment as you wish 

Remember to like and subscribe for more Prankinvasion content 
Mommy make out day

**Comment by spikespaz** [comment]
This is something that I would have considered relevant in the other thread but whatever. I don't really care either way on this matter so I'm not going to put my word in.

**Comment by ghost** [comment]
You closed the other thread, telling people to go to another thread if they wanted to continue talking about it...

**Comment by spikespaz** [comment]
I told them to go to another thread if they wanted to talk about revising *other* channels. Too late now.

**Comment by ghost** [comment]
Yer still closed that issue, oh well.

**Comment by spikespaz** [comment]
It's already been decided in the other issue that the name will not change. Do not create any more duplicate issues.
