### ISSUE TITLE
delete #shoutouts-talk

### ISSUE THREAD

**Issue by ghost** [TheCodeMonkeys/community-suggestions#5]
The context is important sometimes and better off in shoutouts rather thana seperate channel
(context infront of you)

ill never stop

**Comment by bpeters132** [comment]
`#shoutouts-talk` will not go away, and any excessive conversations in `#shoutouts` will keep getting either removed or stopped. Any continuous offenses against this rule (listed in the topic for `#shoutouts`) will result in a mute from the `#shoutouts` channel. 

And you should stop with this meme, or other actions will be considered.

Thank you.
