### ISSUE TITLE
Add #careers

### ISSUE THREAD

**Issue by spikespaz** [TheCodeMonkeys/community-suggestions#6]
For discussing career related things. 

Suggested by @WangzoR.

**Comment by WangzoR** [comment]
Yeah, Careers-Advice or Career/Edu-Help or something, gives people a central location where they can ask about their Education, Future prospects, job seeking, resume writing, interviews.. etc etc you name it

**Comment by bpeters132** [comment]
This sounds like it would be a good channel to have on the server. We will consider adding it.

**Comment by bpeters132** [comment]
#careers channel has been created under the general category.
