### ISSUE TITLE
Merge web-front end and backend

### ISSUE THREAD

**Issue by ghost** [TheCodeMonkeys/community-suggestions#7]
I think backend and front should be merged because one has more activity than the other and skills can be transferred between one another as they are both you know, web.

**Comment by canislupaster** [comment]
Nah, they're very separate. But perhaps we can merge web-backend and software...

**Comment by freaktechnik** [comment]
I think merging the channel won't help with people posting in the "wrong" channel. Both topics are spread over fronted, backend and software in my experience.

**Comment by bpeters132** [comment]
due to a 2v1 vote and nobody else adding input. the web channels will stay separated.
