### ISSUE TITLE
UNO REVERSE CARD

### ISSUE THREAD

**Issue by ghost** [TheCodeMonkeys/community-suggestions#8]
no u

This needs to be done, a uno reverse card emoji is needed for the power of uno card games

Uno miss a turn's next

Required emoji:
![unorev](https://user-images.githubusercontent.com/38193611/40206081-7a3934e4-5a26-11e8-846c-df75dc8af728.jpg)

**Comment by Softizo** [comment]
First of all, the image isn't at a high resolution.

**Comment by ghost** [comment]
I apologies, want a higher res one?
![nou](https://user-images.githubusercontent.com/38193611/40206396-d5c445e6-5a27-11e8-816c-6a364129dc4f.jpg)

and

![reverse](https://user-images.githubusercontent.com/38193611/40206469-1a918a76-5a28-11e8-895f-42be83796f01.jpg)

**Comment by Softizo** [comment]
lol

**Comment by ghost** [comment]
do you think im NOT serious? these emojis need to be put on our minecraft earth

**Comment by bpeters132** [comment]
No
