### ISSUE TITLE
News channel

### ISSUE THREAD

**Issue by canislupaster** [TheCodeMonkeys/community-suggestions#9]
regular updates ppl wants very wow

**Comment by hexed** [comment]
This could be a possibility by using RSS what type of news were you thinking about?

**Comment by canislupaster** [comment]
regular news for regular programmers
i think it should work like this:
unfrequent announcements which usually mention everyone: #announcements
frequent announcements: #shout-outs
random update digests (like all the security xair posts, comics, etc) that wont get buried twice a day: #news

**Comment by ghost** [comment]
Seems a bit silly of an idea, just use shoutouts man , not like loads of people post there each day, and honestly tech news isn’t hard to come by, watch N-O-D-E Dead drop series or something

**Comment by canislupaster** [comment]
discord is my primary source of intelligence :)

**Comment by ghost** [comment]
same, but just use shoutouts

**Comment by freaktechnik** [comment]
I agree with @Cliffside-Dev, it would be very hard to differentiate between things that are shout outs and news.

**Comment by bpeters132** [comment]
Due to a 2v1 vote, #shout-outs is basically news already.
